import { Model, DataTypes } from "../../../deps.ts";

export class Planet extends Model {
  static table = "xgp_planets";

  static fields = {
    planet_id: {
      type: DataTypes.BIG_INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    planet_name: DataTypes.STRING,
    planet_user_id: DataTypes.INTEGER,
    planet_galaxy: DataTypes.INTEGER,
    planet_system: DataTypes.INTEGER,
    planet_planet: DataTypes.INTEGER,
    planet_last_update: DataTypes.INTEGER,
    planet_type: DataTypes.INTEGER,
    planet_destroyed: DataTypes.INTEGER,
    planet_b_building: DataTypes.INTEGER,
    planet_b_building_id: DataTypes.TEXT,
    planet_b_tech: DataTypes.INTEGER,
    planet_b_tech_id: DataTypes.INTEGER,
    planet_b_hangar: DataTypes.INTEGER,
    planet_b_hangar_id: DataTypes.TEXT,
    planet_image: DataTypes.STRING,
    planet_diameter: DataTypes.INTEGER,
    planet_field_current: DataTypes.INTEGER,
    planet_field_max: DataTypes.INTEGER,
    planet_temp_min: DataTypes.INTEGER,
    planet_temp_max: DataTypes.INTEGER,
    planet_metal: DataTypes.DECIMAL,
    planet_metal_perhour: DataTypes.INTEGER,
    planet_metal_max: DataTypes.BIG_INTEGER,
    planet_crystal: DataTypes.DECIMAL,
    planet_crystal_perhour: DataTypes.INTEGER,
    planet_crystal_max: DataTypes.BIG_INTEGER,
    planet_deuterium: DataTypes.DECIMAL,
    planet_deuterium_perhour: DataTypes.INTEGER,
    planet_deuterium_max: DataTypes.BIG_INTEGER,
    planet_energy_used: DataTypes.INTEGER,
    planet_energy_max: DataTypes.BIG_INTEGER,
    planet_building_metal_mine_percent: DataTypes.INTEGER,
    planet_building_crystal_mine_percent: DataTypes.INTEGER,
    planet_building_deuterium_sintetizer_percent: DataTypes.INTEGER,
    planet_building_solar_plant_percent: DataTypes.INTEGER,
    planet_building_fusion_reactor_percent: DataTypes.INTEGER,
    planet_ship_solar_satellite_percent: DataTypes.INTEGER,
    planet_last_jump_time: DataTypes.INTEGER,
    planet_debris_metal: DataTypes.BIG_INTEGER,
    planet_debris_crystal: DataTypes.BIG_INTEGER,
    planet_invisible_start_time: DataTypes.INTEGER,
  };
};